name: 'Eyelash Corne Build'
on:
  push:
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano]'
      shield: '["eyelash_corne_left", "eyelash_corne_right"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'

