name: 'Eyelash Corne Build'
on:
  push:
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["eyelash_corne_left", "eyelash_corne_right"]'
      shield: '["nice_view"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'

